config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => :logout
  get '/auth/failure' => 'sessions#auth_fail'
  get 'intro' => 'home#index', :as => :intro
  
  resources :users do
    post 'location', :on => :member
  end
  
  resources :spotfixes do
    get 'get_lat_lng', :on => :collection
    get 'og_share', :on => :member
    get 'og_invite', :on => :member
    get 'join', :on => :member
    get 'leave', :on => :member
    get 'lead', :on => :member
    get 'unlead', :on => :member    
  end
  
  resources :photos
  resource :attendees
  
  root :to => 'spotfixes#index'

  namespace :api do
    resources :spotfixes do
      get 'join', :on => :member
      get 'leave', :on => :member
      get 'attendees', :on => :member
      get 'spotfixes', :on => :member
      get 'count', :on => :collection
    end
    resources :users do
      get 'spotfixes', :on => :member
      get 'count', :on => :collection
    end
    resources :photos
    resources :needs
    resources :invites
    resources :cities do
      get 'spotfixes', :on => :member
      get 'count', :on => :member
    end
  end

end

app/models/spotfix.rb
class Spotfix < ActiveRecord::Base

  belongs_to :leader, class_name: 'User', foreign_key: 'user_id'
  belongs_to :city
  has_many :needs
  has_many :attendees
  has_many :users, through: :attendees
  has_many :photos
  has_many :invites
  has_many :invited_users, class_name: 'Invite', through: :invites, foreign_key: 'invitee_user_id'

  scope :active, -> { where(active: true) }
  scope :upcoming, -> { where("fix_date >= ?", DateTime.now() + 4.hours ) }
  scope :completed, -> { where("fix_date <= ?", DateTime.now() + 4.hours ) }

  reverse_geocoded_by :latitude, :longitude, :address => :location
  before_create :reverse_geocode, if: ->(obj){ obj.location.nil? }
  before_create :set_name, if: ->(obj){ obj.name.nil? }

  def deactivate
    self.update({ active: false })
  end

  def activate
    self.update({ active: true })
  end

  def info
    '<div id="infoWindow">'+
      "<h4 class='heading'>#{name}</h4>"+
      '<div class="content">'+
      "<div class='info-pic'><img src='#{self.photos.first.image_url(:small)}' align='left'></div>" +
      "<div class='info-text'>#{description}</div>" +
      "<br><br><a href=/spotfixes/#{id}><button type='button' class='view btn btn-primary'>More Details</button></a>" + 
      '</div>'+
      '</div>' +
      '</div>'
  end

  def short_desc
    "#{description[0..50]}..."
  end

  def short_loc
    loc = location.split(",")
    "#{loc[0..(loc.length - 3)].join(",")}"
  end

  def set_name
    self.name = "Fixie ##{13500 + Spotfix.last.id}"
  end

end

app/controllers/api/spotfixes_controller.rb
class Api::SpotfixesController < Api::BaseController

  def index
    @spotfixes = Spotfix.all
  end

  def show
    @spotfix = Spotfix.find(params[:id])
  end

  def create
    @spotfix = Spotfix.new(spotfix_params)
    if @spotfix.save
      if params['photos']
       params['photos']['image'].each do |a|
          @photo = @spotfix.photos.create!(:image => a, :spotfix_id => @spotfix.id)
       end
      end
      unless params['requirements'].blank?
        @need = @spotfix.needs.create!(description: params['requirements'])
      end
      render action: 'show'
    end
  end

  def update
    @spotfix = Spotfix.find(params[:id])
    @spotfix.update!(spotfix_params)
    render action: 'show'
  end

  def destroy
    @spotfix = Spotfix.find(params[:id])
    @spotfix.delete
  end

  def join
    @attendee = Attendee.create(user_id: params[:user_id], spotfix_id: params[:id])
  end

  def leave
    Attendee.where(user_id: params[:user_id], spotfix_id: params[:id]).delete_all
  end

  def attendees
    @attendees = Spotfix.find(params[:id]).attendees
  end

  def count
    @spotfix_count = Spotfix.count
  end

  private

  def spotfix_params
    params.permit(:name, :description, :fix_date, :location, :city_id, :latitude, :longitude)
  end

end

app/controllers/spotfixes_controller.rb
class SpotfixesController < ApplicationController
  layout 'loggedin'
  before_filter :user_signed_in?, :except => [:index, :show, :og_share, :og_invite]
  # before_filter :fetch_location

  def index
    spotfixes = Spotfix.all
    @fixies = spotfixes.collect { |sf| { latitude: sf.latitude, longitude: sf.longitude,  info: sf.info } } 
  end

  def new
    @spotfix = Spotfix.new()  
    @photo = @spotfix.photos.build 
  end

  def show
    @spotfix = Spotfix.find(params[:id])
    @attending = (current_user)? Attendee.where(user_id: current_user.id, spotfix_id: params[:id]).first : nil
  end

  def create
    @spotfix = Spotfix.new(spotfix_params)
    respond_to do |format|
      if @spotfix.save
        if params['photos']
         params['photos']['image'].each do |a|
            @photo = @spotfix.photos.create!(:image => a, :spotfix_id => @spotfix.id)
         end
        end
        unless params['requirements'].blank?
          @need = @spotfix.needs.create!(description: params['requirements'])
        end
       format.html { redirect_to @spotfix, notice: 'Spotfix was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @spotfix = Spotfix.find(params[:id])
  end

  def update
    @spotfix = Spotfix.find(params[:id])
    @spotfix.update!(spotfix_params)
  end

  def destroy
    @spotfix = Spotfix.find(params[:id])
    @spotfix.deactivate
  end

  def join
    @attendee = Attendee.create(user_id: current_user.id, spotfix_id: params[:id])
    redirect_to spotfix_path(params[:id]), notice: "You are now attending this Spotfix"
  end

  def leave
    Attendee.where(user_id: current_user.id, spotfix_id: params[:id]).delete_all
    redirect_to spotfix_path(params[:id]), notice: "You have left this Spotfix"
  end

  def lead
    @spotfix = Spotfix.find(params[:id])
    @spotfix.leader = User.find(params[:user_id])
  end

  def unlead
    @spotfix = Spotfix.find(params[:id])
    if @spotfix.user_id == params[:user_id]
      @spotfix.leader = nil
    end
  end

  def get_lat_lng
    @city = City.find_or_create(params[:city_name])
    render json: @city
  end

  def og_share
    @spotfix = Spotfix.find(params[:id])
    @city = @spotfix.city
    render layout: 'og'
  end

  def og_invite
    @spotfix = Spotfix.find(params[:id])
    @city = @spotfix.city
    render layout: 'og'
  end

  private

  def spotfix_params
    params.permit(:description, :fix_date, :location, :city_id, :latitude, :longitude)
  end

end

app/helpers/spotfix_helper.rb
module SpotfixHelper
end

app/views/spotfixes/index.html.erb
<% content_for :head do %>
    <style type="text/css">
    #map-canvas { height: 100%; width: 100%; margin: 0; padding: 0;}
    </style>
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true">
    </script>
    <script type="text/javascript">
      function initialize() {
        var infowindow = new google.maps.InfoWindow({ 'maxWidth': '300'});
        var points = <%= raw @fixies.to_json %>;
        console.log(points)
        var mapOptions = {
          center: { lat: 22.22809, lng: 79.16748 },
          zoom: 5
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var markers = [];
        console.log(points.length);
        for (var i = 0; i < points.length; i++) {
          console.log(points.length);
          var latLng = new google.maps.LatLng(points[i].latitude,
              points[i].longitude);
          var marker = new google.maps.Marker({'position': latLng, 'info': points[i].info });
          google.maps.event.addListener(marker, 'click', function () {
            infowindow.setContent(this.info);
            infowindow.open(map, this);
          });
          markers.push(marker);
        };
        var markerCluster = new MarkerClusterer(map, markers);
      }

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>


<div class="container">
  <div id="outer-map" style="width:80%; height: 80%; position: absolute; padding: auto;">
    <div id="map-canvas"></div>
  </div>
</div>

app/views/spotfixes/new.html.erb
<% content_for :head do %>
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true">
    </script>
    <script type="text/javascript">
      var marker = null;
      var map = null
      function initialize() {
        var city = <%= raw @city.to_json %>;
        var mapOptions = {
          center: { lat: 12.9715987, lng: 77.5945627 },
          zoom: 12
        };

        map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
        var latLng = new google.maps.LatLng(12.9715987, 77.5945627);
        marker = new google.maps.Marker({'position': latLng, 'map': map, draggable: true});

        var geocoder = new google.maps.Geocoder();
        google.maps.event.addDomListener(document.getElementById("map-func-1"), "click", function() {
          geocoder.geocode({ address: document.getElementById("map-search").value }, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              var result = results[0];
              document.getElementById("map-search").value = result.formatted_address;
              if (result.geometry.viewport) {
                map.fitBounds(result.geometry.viewport);
              } else {
                map.setCenter(result.geometry.location);
              }
            } else if (status == google.maps.GeocoderStatus.ZERO_RESULTS) {
              alert("Sorry, geocoder API failed to locate the address.");
            } else {
              alert("Sorry, geocoder API failed with an error.");
            }
          });
        });

        if (navigator.geolocation) {
          google.maps.event.addDomListener(document.getElementById("map-func-2"), "click", function() {
            navigator.geolocation.getCurrentPosition(function(position) {
              map.setCenter(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
            }, function() {
              alert("Sorry, geolocation API failed to detect your location.");
            });
          });
          document.getElementById("map-func-2").disabled = false;
        }

        google.maps.event.addListener(map, "idle", function() {
          marker.setPosition(map.getCenter());
          $("input#spotfix_latitude").val(map.getCenter().lat())
          $("input#spotfix_longitude").val(map.getCenter().lng())
        });

        google.maps.event.addListener(marker, 'dragend', function (event) {
          $("input#spotfix_latitude").val(this.getPosition().lat());
          $("input#spotfix_longitude").val(this.getPosition().lng());
        });

        $( "input#spotfix_fix_date" ).datepicker({dateFormat: "dd-mm-yy"});

      }
      google.maps.event.addDomListener(window, 'load', initialize);

      $(document).on('click','[data-js_slide_up]',function (e) {
          var slide_ele= $(this).closest($(this).data("js_slide_up"));
          var show_ele=slide_ele.next($(this).data('next_show'));
          slide_ele.slideUp();
          show_ele.removeClass('hide');


        // body...
      });

      $(document).on('keypress', '.enter-city', function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13'){
          $("section.outer-map").show();
          city_name = $(this).val();
          $("section.city-select").slideUp(400);
          console.log(city_name);
          setTimeout(function(){fetchLatLng(city_name)}, 10); 
        }
      });

      //step 2
      $(document).on('click', 'input#map-continue', function(e){
        $("section.outer-map").slideUp(400);
        $("section.form").show();
      });

      //step 1
      $(document).on('click', 'button.city', function(e){
        $("section.outer-map").show();
        city_name = $(this).text();
        $("section.city-select").slideUp(400);
        console.log(city_name);
        setTimeout(function(){fetchLatLng(city_name)}, 10);
      });

      function fetchLatLng(city_name){
        $.ajax({
          type: "GET",
          url: "/spotfixes/get_lat_lng",
          data: { city_name: city_name },
          dataType: 'json'
        })
          .done(function( city ) {
            console.log(city)
            changeMarkerPosition(city.latitude, city.longitude);
            $("input#spotfix_city_id").val(city.id)
          });
      };

      function deleteMarkers(){
        if(typeof marker != 'undefined'){
          marker.setMap(null)
        };
      }

      function changeMarkerPosition(lat,lng){
        console.log(lat + "" + lng);
        var latlng = new google.maps.LatLng(lat,lng);
        marker.setPosition(latlng);
        setTimeout(function(){map.setCenter(latlng)}, 10) ;
        google.maps.event.trigger(map, 'resize');
      };



    </script>
<% end %>

<div class="container">
  <section class="city-select" style="width:80%; height: 80%; position: absolute; ">
    <h1>Enter your city:     <input class="enter-city" id="city" name="city"></h1>
    <h1>or Select
    </h1>
    <p>
    <% City.all.each do |c| %>
    <button class="city label label-info"><%= c.name %></button>
    <% end %>
    </p>
  </section>

  <section class="outer-map" style="width:80%; height: 65%; position: absolute; display: none; max-width: none; display: none;">
    <p style="overflow: hidden;">
      <h1> Now select the exact point of spotfix.
      <input id="map-continue" type="button" value="Continue">
      </h1>
      <input id="map-search" type="text" style="width: 60%; float: left;" value="" maxlength="100">
      <input id="map-func-1" type="button" style="width: 19%; float: left;" value="Locate Address">
      <input id="map-func-2" type="button" style="width: 19%; float: right;" value="Detect Location">
    </p>
    <div id="map-canvas"></div>
  </section>

  <section class="form" style="width:80%; height: 65%; position: absolute; display: none; ">
    <%= bootstrap_form_for(@spotfix, :html => { :multipart => true }) do |f| %>
     <div class="field">
       <%= f.text_field :description %>
     </div>

      <%= f.hidden_field :city_id %>
      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>

      <div class="field">
       <%= f.text_field :fix_date %>
     </div>

     <%= f.fields_for :photos do |p| %>
       <div class="field">
         <%= p.file_field :photo, :multiple => true, name: "photos[image][]" %>
       </div>
     <% end %>

      <div class="field">
        <%= f.text_field :fix_date %>
      </div>

      <div class="field">
        <div class="form-group">
          <label class="control-label" for="requirements">Requirements</label>
          <input class="form-control" id="requirements" name="requirements" type="text">
        </div>
      </div>

      <div class="actions">
      <%= f.submit %>
      </div>
    <% end %>
  </section>
</div>

app/views/spotfixes/og_invite.html.erb
<% content_for :head do %> 
    <meta property="og:title" content="Help me clean <%= @city.name %>" />
    <meta property="og:description" content="I am planning to cleanup a street in <%= @city.name %>. Please join me." /> 
    <meta property="og:image" content="http://utstatic.a.cdnify.io/wp-content/uploads/2013/02/litter2-533x400.jpg" />
    <script> location.href = "<%= spotfix_url(@spotfix.id)%>"; </script>
<% end %>

app/views/spotfixes/og_share.html.erb
<% content_for :head do %> 
    <meta property="og:title" content="Join a Spotix" />
    <meta property="og:description" content="Folks around you are planning to cleanup a street in <%= @city.name %>. Join them now." /> 
    <meta property="og:image" content="http://utstatic.a.cdnify.io/wp-content/uploads/2013/02/litter2-533x400.jpg" />
    <script> location.href = "<%= spotfix_url(@spotfix.id)%>"; </script>
<% end %>

app/views/spotfixes/show.html.erb
<% content_for :head do %> 
    <style type="text/css">
    #map-canvas { height: 100%; width: 100%; margin: 0; padding: 0;}
    </style>
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true">
    </script>
    <script type="text/javascript">

      $(document).ready(function() {
        $.ajaxSetup({ cache: true });
        $.getScript('//connect.facebook.net/en_UK/all.js', function(){
          FB.init({
            appId: <%= Rails.application.secrets['facebook']['app_id'] %>,
          });     
        });
        $("button.share").on('click', function(e){
          FB.ui({
            method: 'share',
            href: "<%= og_share_spotfix_url(@spotfix.id) %>",
          }, function(response){});
        });
        $("button.invite").on('click', function(e){
          FB.ui({
            method: 'send',
            link: "<%= og_invite_spotfix_url(@spotfix.id) %>",
          }, function(response){});
        });
      });

      function initialize() {
        var infowindow = new google.maps.InfoWindow();
        var point = <%= raw @spotfix.to_json %>;
        var mapOptions = {
          center: { lat: point.latitude, lng: point.longitude },
          zoom: 15
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        var latLng = new google.maps.LatLng(point.latitude, point.longitude)
        var marker = new google.maps.Marker({ 'position': latLng, 'map': map });
      }



      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<% end %>


<div class='container' style="margin: 10px auto; border: 1px solid #ccc">
  <div class="row" style=""> 
    <div class="col-md-8">
      <h1 style="text-align: center;"><%= @spotfix.name %></h1>
    </div>
    <div class="col-md-4">
      <div class="row" style="text-align: center;">
        <% if @attending %>
          <%= link_to(leave_spotfix_path(@spotfix.id)) do %>
            <button type="button" class="join btn btn-success">
              Leave
            </button>
          <% end %>
        <% else %>    
          <%= link_to(login_check(join_spotfix_path(@spotfix.id))) do %>
            <button type="button" class="join btn btn-primary">
              Join
            </button>
          <% end %>
        <% end %>
        <button type="button" class="share btn btn-primary">
        Share
        </button>
        <button type="button" class="invite btn btn-primary">
        Invite
        </button>
      </div>
    </div>
  </div>
  <div class="row" style="min-height: 500px; margin-top: 50px;">
    <div class="col-md-8">
        <p style="text-align: center;"><%= @spotfix.short_loc %></p>
        <p style="text-align: center;">To be fixed on: <%= (@spotfix.fix_date.blank?)? 'Not yet decided' : @spotfix.fix_date.strftime("%e %b %Y %H:%M:%S%p") %></p>
        <h2>Description</h2>
        <p><%= (@spotfix.description.blank?)? 'No description was entered' : @spotfix.description %></p>
        <h2>Photos</h2>
        <p>Before:</p>
        <p>
        <% if @spotfix.photos.empty? %>
          No pics uploaded
        <% else %>
          <% @spotfix.photos.each do |p| %>
            <%= image_tag p.image_url(:medium) %>
          <% end %>
        <% end %>
        </p>
        <p>After:<br>
        Please add some pics once this gets over.
        </p>
        <h2>Requirements</h2>
        <p>
        <%= (@spotfix.needs.blank?)? 'No requirement was entered' : @spotfix.needs.first.description %>
        </p>

    </div>

    <div class="col-md-4" style="min-height: 500px">

      <div id="outer-map" style="width:80%; height: 80%; position: absolute; padding: auto;">
        <div id="map-canvas"></div>
      </div>
    </div>
  </div>
</div>